# NOTE: Archived workflow. Manual runs only.
# Moved by scripts/archive_non_unified_workflows_v2_9.mjs
# Original file name: lessons-validate.yml
name: Lessons · Validate

on:
  workflow_dispatch: {}
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      LESSONS_TARGET_VERSION: v2.4.7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - name: Debug – show validator script & target
        run: |
          node -e "import fs from 'fs'; const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); console.log('validator:', pkg.scripts['validate:lessons']); console.log('LESSONS_TARGET_VERSION=' + (process.env.LESSONS_TARGET_VERSION || ''));"
      - name: Validate lessons (authoritative)
        run: npm run validate:lessons
      - name: Validate drift
        run: npm run validate:drift
