name: Backlog · Health (Curated Only)
on:
  push:
    branches: [ main, backlog-reset-v1 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Check curated tickets (no placeholders, quality ≥ 70 before promotion)
        run: |
          set -e
          echo "Scanning tickets for literal 'Placeholder' (case-insensitive)…"
          MATCHES=$(grep -Rni "Placeholder" tickets || true)
          if [ -n "$MATCHES" ]; then
            echo "$MATCHES"
            echo "::error::Placeholder found in curated tickets"
            exit 1
          fi
          echo "OK: no 'Placeholder' matches."
      - name: Matrix basic sanity
        run: |
          set -e
          FILE="artefacts/logs/backlog_matrix_v1.1.md"
          test -f "$FILE" || (echo "::error::missing v1.1 matrix" && exit 1)
          cols=$(awk -F"|" '
            BEGIN{h=0}
            /^\|/{h++; if(h==1){print NF-2; exit}}
          ' "$FILE")
          if [ -z "${cols:-}" ]; then
            echo "::error::no table header found"; exit 1
          fi
          [ "$cols" -ge 11 ] || (echo "::error::matrix header has <11 columns (got=$cols)" && exit 1)
