name: Backlog · Health (Curated Only)
on:
  push:
    branches: [ main, backlog-reset-v1 ]
    paths-ignore:
      - 'archive/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'archive/**'
  workflow_dispatch:

jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      v2: ${{ steps.detect.outputs.v2 }}
      intent: ${{ steps.detect.outputs.intent }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        shell: bash
        run: |
          set -e
          if [[ -f meta/CORE_INDEX_v2.0.md ]]; then echo "v2=true" >> $GITHUB_OUTPUT; else echo "v2=false" >> $GITHUB_OUTPUT; fi
          intent=unknown
          if [[ -f meta/AI_First_Roadmap_v2.0.md ]]; then
            if grep -qE 'intent_state:\s*confirmed' meta/AI_First_Roadmap_v2.0.md; then intent=confirmed
            elif grep -qE 'intent_state:\s*draft' meta/AI_First_Roadmap_v2.0.md; then intent=draft
            fi
          fi
          echo "intent=$intent" >> $GITHUB_OUTPUT

  health:
    needs: mode
    if: needs.mode.outputs.v2 == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Check curated tickets (no placeholders, quality ≥ 70 before promotion)
        run: |
          set -e
          echo "Scanning tickets for literal 'Placeholder' (case-insensitive)…"
          MATCHES=$(grep -Rni "Placeholder" tickets || true)
          if [ -n "$MATCHES" ]; then
            echo "$MATCHES"
            echo "::error::Placeholder found in curated tickets"
            exit 1
          fi
          echo "OK: no 'Placeholder' matches."
      - name: Matrix basic sanity
        run: |
          set -e
          FILE="artefacts/logs/backlog_matrix_v1.1.md"
          test -f "$FILE" || (echo "::error::missing v1.1 matrix" && exit 1)
          cols=$(awk -F"|" '
            BEGIN{h=0}
            /^\|/{h++; if(h==1){print NF-2; exit}}
          ' "$FILE")
          if [ -z "${cols:-}" ]; then
            echo "::error::no table header found"; exit 1
          fi
          [ "$cols" -ge 11 ] || (echo "::error::matrix header has <11 columns (got=$cols)" && exit 1)

  health-v2:
    needs: mode
    if: needs.mode.outputs.v2 == 'true' && needs.mode.outputs.intent == 'confirmed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: v2 skeleton sanity
        shell: bash
        run: |
          set -e
          test -f meta/AI_First_System_Architecture_v2.0.md
          test -f meta/AI_First_Roadmap_v2.0.md
          test -f meta/AI_First_Handbook_v2.0.md
          test -f meta/Human_in_the_Loop_Playbook_v2.0.md
          test -f docs/AI_First_Business_Case_v2.0.md
          echo "v2 skeleton ok (intent confirmed)"
