# Legacy Notice:
# Dieser Workflow bleibt für historische Diagnosezwecke erhalten,
# wird jedoch ab AT-028 durch den konsolidierten CI-Layer (Meta Diagnose) ersetzt.
# Status: legacy (nicht aktiv mergen)

name: CI · Deep Diagnose v1.1
on:
  push:
    paths-ignore:
      - 'archive/**'
  pull_request:
    paths-ignore:
      - 'archive/**'
  schedule:
    - cron: "0 6 * * 1"   # Mo 06:00 UTC
jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      v2: ${{ steps.detect.outputs.v2 }}
      intent: ${{ steps.detect.outputs.intent }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        shell: bash
        run: |
          set -e
          if [[ -f meta/CORE_INDEX_v2.0.md ]]; then echo "v2=true" >> $GITHUB_OUTPUT; else echo "v2=false" >> $GITHUB_OUTPUT; fi
          intent=unknown
          if [[ -f meta/AI_First_Roadmap_v2.0.md ]]; then
            if grep -qE 'intent_state:\s*confirmed' meta/AI_First_Roadmap_v2.0.md; then intent=confirmed
            elif grep -qE 'intent_state:\s*draft' meta/AI_First_Roadmap_v2.0.md; then intent=draft
            fi
          fi
          echo "intent=$intent" >> $GITHUB_OUTPUT

  deep-diagnose:
    needs: mode
    if: needs.mode.outputs.v2 == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run Deep Diagnose (tolerate warnings)
        id: run
        continue-on-error: true
        run: node scripts/deep_diagnose_repo_v1_1.mjs
      - name: Upload Deep Diagnose Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deep-diagnose-v1_1
          path: |
            artefacts/logs/deep_diagnose_v1_1.md
            artefacts/logs/deep_diagnose_v1_1.json
      - name: Classify outcome
        if: always()
        run: |
          CODE=$(node -e "const fs=require('fs');let c=0;try{c=JSON.parse(fs.readFileSync('artefacts/logs/deep_diagnose_v1_1.json','utf8')).exit_code??0;}catch(e){c=1}process.stdout.write(String(c));")
          echo "exit=$CODE"
          if [ "$CODE" -eq 1 ]; then
            echo '::error::Deep Diagnose failed (exit=1).'; exit 1
          elif [ "$CODE" -eq 2 ]; then
            echo '::warning::Deep Diagnose warnings (exit=2).'; exit 0
          else
            echo 'Deep Diagnose passed.'; exit 0
          fi

  health-v2:
    needs: mode
    if: needs.mode.outputs.v2 == 'true' && needs.mode.outputs.intent == 'confirmed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: v2 skeleton sanity
        shell: bash
        run: |
          set -e
          test -f meta/AI_First_System_Architecture_v2.0.md
          test -f meta/AI_First_Roadmap_v2.0.md
          test -f meta/AI_First_Handbook_v2.0.md
          test -f meta/Human_in_the_Loop_Playbook_v2.0.md
          test -f docs/AI_First_Business_Case_v2.0.md
          echo "v2 skeleton ok (intent confirmed)"
