name: P-CORE · Daily Diagnostics (read-only)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 6 * * 1-5" # optional: Werktags 06:15 UTC

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write   # nötig für actions/upload-artifact
    steps:
      - name: Checkout (read-only)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run diagnostics (read-only)
        id: diag
        run: node scripts/diag_p_core.mjs

      - name: Upload JSON snapshot
        uses: actions/upload-artifact@v4
        with:
          name: diag_p_core_snapshot
          path: ${{ runner.temp }}/diag_p_core_snapshot_*.json
          if-no-files-found: error
