name: Handbook · Enforcement (Safe Start, Refined)
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate Handbook Compliance (manual)
        run: node scripts/validate_handbook.mjs

# HINWEIS (SPÄTER, wenn stabil):
# - VALIDATOR_MODE entfernen (oder auf 'strict' setzen, ENV weglassen)
# - Trigger umstellen:
#   on:
#     pull_request:
#       types: [opened, edited, synchronize]
