name: Ledger Mirror · Sessions (non-blocking)
on:
  schedule:
    - cron: "23 4 * * *"
  workflow_dispatch:
jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      v2: ${{ steps.detect.outputs.v2 }}
      intent: ${{ steps.detect.outputs.intent }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        shell: bash
        run: |
          set -e
          if [[ -f meta/CORE_INDEX_v2.0.md ]]; then echo "v2=true" >> $GITHUB_OUTPUT; else echo "v2=false" >> $GITHUB_OUTPUT; fi
          intent=unknown
          if [[ -f meta/AI_First_Roadmap_v2.0.md ]]; then
            if grep -qE 'intent_state:\s*confirmed' meta/AI_First_Roadmap_v2.0.md; then intent=confirmed
            elif grep -qE 'intent_state:\s*draft' meta/AI_First_Roadmap_v2.0.md; then intent=draft
            fi
          fi
          echo "intent=$intent" >> $GITHUB_OUTPUT

  mirror:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Analyze sessions (ensure JSON exists)
        run: |
          node scripts/analyze_sessions.mjs --threshold-min=120 --min-session-min=10 || true
      - name: Mirror to Ledger
        run: |
          node scripts/sync_time_sessions_to_ledger.mjs || true
      - name: Show ledger excerpt
        run: sed -n '1,120p' artefacts/sync/System_Harmony_Ledger.md || true
      - name: Heartbeat
        run: echo "HEARTBEAT ✓ $(date -u +%FT%TZ) · Ledger Mirror OK"
