name: ledger-validate
on:
  push:
    paths-ignore:
      - 'archive/**'
  pull_request:
    paths-ignore:
      - 'archive/**'
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 0" # So 16:00 UTC (So 18:00 lokal ~ Beispiel)
jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      v2: ${{ steps.detect.outputs.v2 }}
      intent: ${{ steps.detect.outputs.intent }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        shell: bash
        run: |
          set -e
          if [[ -f meta/CORE_INDEX_v2.0.md ]]; then echo "v2=true" >> $GITHUB_OUTPUT; else echo "v2=false" >> $GITHUB_OUTPUT; fi
          intent=unknown
          if [[ -f meta/AI_First_Roadmap_v2.0.md ]]; then
            if grep -qE 'intent_state:\s*confirmed' meta/AI_First_Roadmap_v2.0.md; then intent=confirmed
            elif grep -qE 'intent_state:\s*draft' meta/AI_First_Roadmap_v2.0.md; then intent=draft
            fi
          fi
          echo "intent=$intent" >> $GITHUB_OUTPUT

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run Ledger Validation (pilot, tolerate warnings)
        continue-on-error: true
        env:
          MAX_DRIFT_WARN: "5"
          MIN_HEALTH_WARN: "90"
          HARMONY_EXPECTED_GREEN: "false"
        run: node scripts/validate_ledger.mjs --max-drift=5 --min-health=80

      - name: Classify outcome (set job conclusion)
        if: always()
        run: |
          echo "status: postprocess | reading artefacts/logs/validator_exit.json"
          code=$(jq -r '.exit // "0"' artefacts/logs/validator_exit.json 2>/dev/null || echo "0")
          echo "validator_exit=$code"
          if [ "$code" = "1" ]; then
            echo "::error::Ledger validation failed (exit=1)."
            exit 1
          elif [ "$code" = "2" ]; then
            echo "::warning::Ledger validation reported warnings (exit=2)."
            exit 0
          else
            echo "Ledger validation passed."
            exit 0
          fi
