name: Ledger Mirror · Sessions (non-blocking)
on:
  schedule:
    - cron: "23 4 * * *"
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Analyze sessions (ensure JSON exists)
        run: |
          node scripts/analyze_sessions.mjs --threshold-min=120 --min-session-min=10 || true
      - name: Mirror to Ledger
        run: |
          node scripts/sync_time_sessions_to_ledger.mjs || true
      - name: Show ledger excerpt
        run: sed -n '1,120p' artefacts/sync/System_Harmony_Ledger.md || true
