name: CI · Meta Diagnose v1.8
on:
  push:
    paths-ignore:
      - 'archive/**'
  pull_request:
    paths-ignore:
      - 'archive/**'
  schedule:
    - cron: "0 7 * * 1" # Mo 07:00 UTC
jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      v2: ${{ steps.detect.outputs.v2 }}
      intent: ${{ steps.detect.outputs.intent }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        shell: bash
        run: |
          set -e
          if [[ -f meta/CORE_INDEX_v2.0.md ]]; then echo "v2=true" >> $GITHUB_OUTPUT; else echo "v2=false" >> $GITHUB_OUTPUT; fi
          intent=unknown
          if [[ -f meta/AI_First_Roadmap_v2.0.md ]]; then
            if grep -qE 'intent_state:\s*confirmed' meta/AI_First_Roadmap_v2.0.md; then intent=confirmed
            elif grep -qE 'intent_state:\s*draft' meta/AI_First_Roadmap_v2.0.md; then intent=draft
            fi
          fi
          echo "intent=$intent" >> $GITHUB_OUTPUT

  meta-diagnose:
    needs: mode
    if: needs.mode.outputs.v2 == 'false'
    runs-on: ubuntu-latest
    defaults: { run: { shell: bash } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run Meta Diagnose (tolerate warnings)
        id: run_meta
        continue-on-error: true
        run: node scripts/run_meta_diagnose_v1_8.mjs
      - name: Upload Meta Diagnose Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: meta-diagnose-v1_8-reports
          path: |
            artefacts/logs/meta/diagnose_meta_v1.8.md
            artefacts/logs/meta/diagnose_meta_v1.8.json
      - name: Classify outcome (fail on missing report / non-success run)
        if: always()
        env:
          RUN_OUTCOME: ${{ steps.run_meta.outcome }}
        run: |
          echo "run_outcome=$RUN_OUTCOME"
          REPORT="artefacts/logs/meta/diagnose_meta_v1.8.json"
          if [ "$RUN_OUTCOME" != "success" ]; then
            echo "::error::Meta diagnose step did not complete successfully (outcome=$RUN_OUTCOME)."
            [ -f "$REPORT" ] || exit 1
          fi
          if [ ! -f "$REPORT" ]; then
            echo "::error::Missing report $REPORT – diagnose likely crashed."; exit 1
          fi
          CODE=$(node -e "const fs=require('fs');let c=0;try{const j=JSON.parse(fs.readFileSync('artefacts/logs/meta/diagnose_meta_v1.8.json','utf8'));c=(j.exit_code??0);}catch(e){c=1;}process.stdout.write(String(c));")
          echo "exit=$CODE"
          if [ "$CODE" -eq 1 ]; then
            echo '::error::Meta Diagnose failed (exit=1).'; exit 1
          elif [ "$CODE" -eq 2 ]; then
            echo '::warning::Meta Diagnose warnings (exit=2).'; exit 0
          else
            echo 'Meta Diagnose passed.'; exit 0
          fi

  health-v2:
    needs: mode
    if: needs.mode.outputs.v2 == 'true' && needs.mode.outputs.intent == 'confirmed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: v2 skeleton sanity
        shell: bash
        run: |
          set -e
          test -f meta/AI_First_System_Architecture_v2.0.md
          test -f meta/AI_First_Roadmap_v2.0.md
          test -f meta/AI_First_Handbook_v2.0.md
          test -f meta/Human_in_the_Loop_Playbook_v2.0.md
          test -f docs/AI_First_Business_Case_v2.0.md
          echo "v2 skeleton ok (intent confirmed)"
