name: Sanity · Core Docs
on:
  pull_request:
    paths:
      - docs/**
      - meta/**
      - meta/system_version.json
      - .github/workflows/sanity.yml
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          set -e
          echo "Checking core docs exist (stable paths)…"
          test -f docs/AI_First_Business_Case.md
          test -f meta/AI_First_Handbook.md
          test -f meta/AI_First_Roadmap.md
          test -f meta/AI_First_System_Architecture.md
          test -f meta/Human_in_the_Loop_Playbook.md
          test -f meta/Prompt_Inventory.md
          test -f meta/CORE_INDEX.md
          echo "OK"
