name: CI · Trust Probe v1.9.1
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'archive/**'
  schedule:
    - cron: "17 3 * * *"
jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      v2: ${{ steps.detect.outputs.v2 }}
      intent: ${{ steps.detect.outputs.intent }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        shell: bash
        run: |
          set -e
          if [[ -f meta/CORE_INDEX_v2.0.md ]]; then echo "v2=true" >> $GITHUB_OUTPUT; else echo "v2=false" >> $GITHUB_OUTPUT; fi
          intent=unknown
          if [[ -f meta/AI_First_Roadmap_v2.0.md ]]; then
            if grep -qE 'intent_state:\s*confirmed' meta/AI_First_Roadmap_v2.0.md; then intent=confirmed
            elif grep -qE 'intent_state:\s*draft' meta/AI_First_Roadmap_v2.0.md; then intent=draft
            fi
          fi
          echo "intent=$intent" >> $GITHUB_OUTPUT

  probe:
    needs: mode
    if: needs.mode.outputs.v2 == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: node scripts/proof_log_agg.mjs --min-coverage 0.95 --log artefacts/logs/proofs/proof_log.csv
      - run: node scripts/validate_energy.mjs --min-erio 1.1 --feed artefacts/data/sbi/sbi_energy.csv
      - run: node scripts/run_trust_probe_v1_9_1.mjs

  health-v2:
    needs: mode
    if: needs.mode.outputs.v2 == 'true' && needs.mode.outputs.intent == 'confirmed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: v2 skeleton sanity
        shell: bash
        run: |
          set -e
          test -f meta/AI_First_System_Architecture_v2.0.md
          test -f meta/AI_First_Roadmap_v2.0.md
          test -f meta/AI_First_Handbook_v2.0.md
          test -f meta/Human_in_the_Loop_Playbook_v2.0.md
          test -f docs/AI_First_Business_Case_v2.0.md
          echo "v2 skeleton ok (intent confirmed)"
